-- =============================================================================
-- Supabase Schema for MultiBot Payment System
-- Multi-Bot, Multi-Configuration & Isolated Referral Support
-- =============================================================================

-- 1. Tabel Master Bot (Multi-Bot Registry)
CREATE TABLE IF NOT EXISTS public.vip_bots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_code TEXT NOT NULL UNIQUE,
    bot_token TEXT NOT NULL UNIQUE,
    bot_username TEXT NOT NULL DEFAULT '',
    bot_name TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'stopped')),
    sociabuzz_username TEXT DEFAULT NULL,
    sociabuzz_cookie TEXT DEFAULT NULL,
    log_chat_id BIGINT DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vip_bots_status ON public.vip_bots (status);
ALTER TABLE public.vip_bots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vip_bots FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.vip_bots TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vip_bots_id_seq TO service_role;

-- 2. Tabel Payments (Transaksi & Invoice)
CREATE TABLE IF NOT EXISTS public.vip_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_code TEXT NOT NULL DEFAULT 'default',
    user_id BIGINT NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    package_code TEXT NOT NULL DEFAULT '',
    package_name TEXT NOT NULL DEFAULT '',
    package_amount INTEGER NOT NULL DEFAULT 0,
    vip_chat_id BIGINT,
    invite_expire_hours INTEGER NOT NULL DEFAULT 0,
    public_invoice_id TEXT NOT NULL,
    order_id TEXT NOT NULL UNIQUE,
    payment_url TEXT NOT NULL,
    inv_id TEXT NOT NULL UNIQUE,
    amount INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN (
            'pending',
            'processing_paid',
            'invite_error',
            'processing_delivery',
            'delivery_error',
            'delivery_blocked',
            'paid',
            'failed_or_expired',
            'unknown',
            'poll_error',
            'timeout'
        )
    ),
    buyer_name TEXT NOT NULL,
    buyer_email TEXT NOT NULL,
    qris_amount TEXT NOT NULL DEFAULT '',
    qris_expires TEXT NOT NULL DEFAULT '',
    qris_chat_id BIGINT,
    qris_message_id BIGINT,
    next_check_at TIMESTAMPTZ,
    poll_attempts INTEGER NOT NULL DEFAULT 0,
    last_polled_at TIMESTAMPTZ,
    invite_link TEXT,
    invite_expires_at TIMESTAMPTZ,
    error TEXT NOT NULL DEFAULT '',
    referral_id BIGINT,
    referrer_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS bot_code TEXT NOT NULL DEFAULT 'default';
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS public_invoice_id TEXT;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS package_code TEXT NOT NULL DEFAULT '';
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS package_name TEXT NOT NULL DEFAULT '';
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS package_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS vip_chat_id BIGINT;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS invite_expire_hours INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS qris_chat_id BIGINT;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS qris_message_id BIGINT;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS next_check_at TIMESTAMPTZ;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS poll_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS last_polled_at TIMESTAMPTZ;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS referral_id BIGINT;
ALTER TABLE public.vip_payments ADD COLUMN IF NOT EXISTS referrer_user_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_vip_payments_bot_code ON public.vip_payments (bot_code);
CREATE INDEX IF NOT EXISTS idx_vip_payments_user_status ON public.vip_payments (bot_code, user_id, status, id DESC);
CREATE INDEX IF NOT EXISTS idx_vip_payments_status_id ON public.vip_payments (status, id ASC);
CREATE INDEX IF NOT EXISTS idx_vip_payments_next_check ON public.vip_payments (next_check_at ASC, id ASC) WHERE status IN ('pending', 'invite_error', 'delivery_error');
CREATE UNIQUE INDEX IF NOT EXISTS idx_vip_payments_public_invoice_id ON public.vip_payments (public_invoice_id);

-- One active payment per user per bot
DROP INDEX IF EXISTS idx_vip_payments_one_active_per_user;
CREATE UNIQUE INDEX IF NOT EXISTS idx_vip_payments_one_active_per_user
ON public.vip_payments (bot_code, user_id)
WHERE status IN ('pending', 'processing_paid', 'invite_error', 'processing_delivery', 'delivery_error');

ALTER TABLE public.vip_payments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vip_payments FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_payments TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vip_payments_id_seq TO service_role;

-- 3. Tabel Settings Global
CREATE TABLE IF NOT EXISTS public.vip_bot_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.vip_bot_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vip_bot_settings FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_bot_settings TO service_role;

-- 4. Tabel Packages (Scoped per bot_code)
CREATE TABLE IF NOT EXISTS public.vip_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bot_code TEXT NOT NULL DEFAULT 'default',
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    vip_chat_id BIGINT NOT NULL,
    amount INTEGER NOT NULL CHECK (amount >= 1000 AND amount <= 10000000),
    invite_expire_hours INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (bot_code, code)
);

ALTER TABLE public.vip_packages ADD COLUMN IF NOT EXISTS bot_code TEXT NOT NULL DEFAULT 'default';
ALTER TABLE public.vip_packages ADD COLUMN IF NOT EXISTS invite_expire_hours INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.vip_packages ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.vip_packages ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 100;

CREATE INDEX IF NOT EXISTS idx_vip_packages_bot_active ON public.vip_packages (bot_code, active, sort_order ASC);
ALTER TABLE public.vip_packages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vip_packages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.vip_packages TO service_role;

-- 5. Tabel Users (Scoped per bot_code untuk isolasi saldo & referral)
CREATE TABLE IF NOT EXISTS public.vip_users (
    bot_code TEXT NOT NULL DEFAULT 'default',
    user_id BIGINT NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    referral_code TEXT NOT NULL,
    invited_by_user_id BIGINT,
    balance INTEGER NOT NULL DEFAULT 0,
    pending_referrals INTEGER NOT NULL DEFAULT 0,
    successful_referrals INTEGER NOT NULL DEFAULT 0,
    is_bot BOOLEAN NOT NULL DEFAULT false,
    last_broadcast_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (bot_code, user_id)
);

ALTER TABLE public.vip_users ADD COLUMN IF NOT EXISTS bot_code TEXT NOT NULL DEFAULT 'default';
ALTER TABLE public.vip_users ADD COLUMN IF NOT EXISTS is_bot BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.vip_users ADD COLUMN IF NOT EXISTS last_broadcast_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_vip_users_bot_referral_code ON public.vip_users (bot_code, referral_code);
CREATE INDEX IF NOT EXISTS idx_vip_users_bot_invited_by ON public.vip_users (bot_code, invited_by_user_id);
CREATE INDEX IF NOT EXISTS idx_vip_users_broadcast_order ON public.vip_users (bot_code, is_bot, last_broadcast_at ASC NULLS FIRST, user_id);

ALTER TABLE public.vip_users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vip_users FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_users TO service_role;

-- 6. Tabel Referrals (Scoped per bot_code)
CREATE TABLE IF NOT EXISTS public.vip_referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_code TEXT NOT NULL DEFAULT 'default',
    referrer_user_id BIGINT NOT NULL,
    referrer_code TEXT NOT NULL,
    invited_user_id BIGINT NOT NULL,
    invited_username TEXT NOT NULL DEFAULT '',
    invited_full_name TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    payment_inv_id TEXT,
    package_code TEXT NOT NULL DEFAULT '',
    package_amount INTEGER NOT NULL DEFAULT 0,
    commission_amount INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.vip_referrals ADD COLUMN IF NOT EXISTS bot_code TEXT NOT NULL DEFAULT 'default';
DROP INDEX IF EXISTS idx_vip_referrals_bot_invited;
CREATE UNIQUE INDEX IF NOT EXISTS idx_vip_referrals_bot_invited ON public.vip_referrals (bot_code, invited_user_id);
CREATE INDEX IF NOT EXISTS idx_vip_referrals_bot_referrer_status ON public.vip_referrals (bot_code, referrer_user_id, status, id DESC);
CREATE INDEX IF NOT EXISTS idx_vip_referrals_referrer_code ON public.vip_referrals (bot_code, referrer_code);

ALTER TABLE public.vip_referrals ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vip_referrals FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_referrals TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vip_referrals_id_seq TO service_role;

-- 7. Tabel Withdrawals (Scoped per bot_code)
CREATE TABLE IF NOT EXISTS public.vip_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_code TEXT NOT NULL DEFAULT 'default',
    user_id BIGINT NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    amount INTEGER NOT NULL CHECK (amount > 0),
    phone TEXT NOT NULL,
    wallet_name TEXT NOT NULL,
    account_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'rejected')),
    admin_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.vip_withdrawals ADD COLUMN IF NOT EXISTS bot_code TEXT NOT NULL DEFAULT 'default';
CREATE INDEX IF NOT EXISTS idx_vip_withdrawals_bot_user_status ON public.vip_withdrawals (bot_code, user_id, status, id DESC);
CREATE INDEX IF NOT EXISTS idx_vip_withdrawals_bot_status ON public.vip_withdrawals (bot_code, status, id DESC);

ALTER TABLE public.vip_withdrawals ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vip_withdrawals FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_withdrawals TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vip_withdrawals_id_seq TO service_role;

-- 8. Tabel Broadcast
CREATE TABLE IF NOT EXISTS public.vip_broadcast_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_code TEXT NOT NULL DEFAULT 'default',
    message_text TEXT NOT NULL DEFAULT '',
    media_telegram_file_id TEXT NOT NULL DEFAULT '',
    media_type TEXT NOT NULL DEFAULT '',
    entities_json TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.vip_broadcast_messages ADD COLUMN IF NOT EXISTS bot_code TEXT NOT NULL DEFAULT 'default';
ALTER TABLE public.vip_broadcast_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vip_broadcast_messages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_broadcast_messages TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vip_broadcast_messages_id_seq TO service_role;

-- 9. RPC Functions (dengan parameter p_bot_code)

CREATE OR REPLACE FUNCTION public.vip_increment_pending_referral(p_user_id BIGINT, p_bot_code TEXT DEFAULT 'default')
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS 
    UPDATE public.vip_users
    SET pending_referrals = pending_referrals + 1,
        updated_at = now()
    WHERE user_id = p_user_id AND bot_code = p_bot_code;
;

CREATE OR REPLACE FUNCTION public.vip_credit_referral_commission(p_user_id BIGINT, p_amount INTEGER, p_bot_code TEXT DEFAULT 'default')
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS 
    UPDATE public.vip_users
    SET balance = balance + GREATEST(p_amount, 0),
        pending_referrals = GREATEST(pending_referrals - 1, 0),
        successful_referrals = successful_referrals + 1,
        updated_at = now()
    WHERE user_id = p_user_id AND bot_code = p_bot_code;
;

CREATE OR REPLACE FUNCTION public.vip_credit_balance(p_user_id BIGINT, p_amount INTEGER, p_bot_code TEXT DEFAULT 'default')
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS 
    UPDATE public.vip_users
    SET balance = balance + GREATEST(p_amount, 0),
        updated_at = now()
    WHERE user_id = p_user_id AND bot_code = p_bot_code;
;

CREATE OR REPLACE FUNCTION public.vip_create_withdrawal(
    p_user_id BIGINT,
    p_username TEXT,
    p_full_name TEXT,
    p_amount INTEGER,
    p_phone TEXT,
    p_wallet_name TEXT,
    p_account_name TEXT,
    p_bot_code TEXT DEFAULT 'default'
)
RETURNS SETOF public.vip_withdrawals
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS 
DECLARE
    created public.vip_withdrawals;
BEGIN
    IF p_amount < 10000 THEN
        RETURN;
    END IF;

    UPDATE public.vip_users
    SET balance = balance - p_amount,
        phone = p_phone,
        updated_at = now()
    WHERE user_id = p_user_id
      AND bot_code = p_bot_code
      AND balance >= p_amount;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    INSERT INTO public.vip_withdrawals (
        bot_code,
        user_id,
        username,
        full_name,
        amount,
        phone,
        wallet_name,
        account_name,
        status,
        created_at,
        updated_at
    ) VALUES (
        p_bot_code,
        p_user_id,
        p_username,
        p_full_name,
        p_amount,
        p_phone,
        p_wallet_name,
        p_account_name,
        'pending',
        now(),
        now()
    ) RETURNING * INTO created;

    RETURN NEXT created;
END;
;

REVOKE ALL ON FUNCTION public.vip_increment_pending_referral(BIGINT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.vip_credit_referral_commission(BIGINT, INTEGER, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.vip_credit_balance(BIGINT, INTEGER, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.vip_create_withdrawal(BIGINT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.vip_increment_pending_referral(BIGINT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.vip_credit_referral_commission(BIGINT, INTEGER, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.vip_credit_balance(BIGINT, INTEGER, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.vip_create_withdrawal(BIGINT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT) TO service_role;
